
// -*- C++ -*-
// $Id: ProcessorProbe_Impl_Export.h 1754 2011-02-20 23:56:20Z owensh $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl PROCESSORPROBE_IMPL
// ------------------------------
#ifndef PROCESSORPROBE_IMPL_EXPORT_H
#define PROCESSORPROBE_IMPL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (PROCESSORPROBE_IMPL_HAS_DLL)
#  define PROCESSORPROBE_IMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && PROCESSORPROBE_IMPL_HAS_DLL */

#if !defined (PROCESSORPROBE_IMPL_HAS_DLL)
#  define PROCESSORPROBE_IMPL_HAS_DLL 1
#endif /* ! PROCESSORPROBE_IMPL_HAS_DLL */

#if defined (PROCESSORPROBE_IMPL_HAS_DLL) && (PROCESSORPROBE_IMPL_HAS_DLL == 1)
#  if defined (PROCESSORPROBE_IMPL_BUILD_DLL)
#    define PROCESSORPROBE_IMPL_Export ACE_Proper_Export_Flag
#    define PROCESSORPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define PROCESSORPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* PROCESSORPROBE_IMPL_BUILD_DLL */
#    define PROCESSORPROBE_IMPL_Export ACE_Proper_Import_Flag
#    define PROCESSORPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define PROCESSORPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* PROCESSORPROBE_IMPL_BUILD_DLL */
#else /* PROCESSORPROBE_IMPL_HAS_DLL == 1 */
#  define PROCESSORPROBE_IMPL_Export
#  define PROCESSORPROBE_IMPL_SINGLETON_DECLARATION(T)
#  define PROCESSORPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* PROCESSORPROBE_IMPL_HAS_DLL == 1 */

// Set PROCESSORPROBE_IMPL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (PROCESSORPROBE_IMPL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define PROCESSORPROBE_IMPL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define PROCESSORPROBE_IMPL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !PROCESSORPROBE_IMPL_NTRACE */

#if (PROCESSORPROBE_IMPL_NTRACE == 1)
#  define PROCESSORPROBE_IMPL_TRACE(X)
#else /* (PROCESSORPROBE_IMPL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define PROCESSORPROBE_IMPL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (PROCESSORPROBE_IMPL_NTRACE == 1) */

#endif /* PROCESSORPROBE_IMPL_EXPORT_H */

// End of auto generated file.
