
// -*- C++ -*-
// $Id: NetworkProbe_Impl_export.h 1754 2011-02-20 23:56:20Z owensh $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl NETWORKPROBE_IMPL
// ------------------------------
#ifndef NETWORKPROBE_IMPL_EXPORT_H
#define NETWORKPROBE_IMPL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (NETWORKPROBE_IMPL_HAS_DLL)
#  define NETWORKPROBE_IMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && NETWORKPROBE_IMPL_HAS_DLL */

#if !defined (NETWORKPROBE_IMPL_HAS_DLL)
#  define NETWORKPROBE_IMPL_HAS_DLL 1
#endif /* ! NETWORKPROBE_IMPL_HAS_DLL */

#if defined (NETWORKPROBE_IMPL_HAS_DLL) && (NETWORKPROBE_IMPL_HAS_DLL == 1)
#  if defined (NETWORKPROBE_IMPL_BUILD_DLL)
#    define NETWORKPROBE_IMPL_Export ACE_Proper_Export_Flag
#    define NETWORKPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define NETWORKPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* NETWORKPROBE_IMPL_BUILD_DLL */
#    define NETWORKPROBE_IMPL_Export ACE_Proper_Import_Flag
#    define NETWORKPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define NETWORKPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* NETWORKPROBE_IMPL_BUILD_DLL */
#else /* NETWORKPROBE_IMPL_HAS_DLL == 1 */
#  define NETWORKPROBE_IMPL_Export
#  define NETWORKPROBE_IMPL_SINGLETON_DECLARATION(T)
#  define NETWORKPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* NETWORKPROBE_IMPL_HAS_DLL == 1 */

// Set NETWORKPROBE_IMPL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (NETWORKPROBE_IMPL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define NETWORKPROBE_IMPL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define NETWORKPROBE_IMPL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !NETWORKPROBE_IMPL_NTRACE */

#if (NETWORKPROBE_IMPL_NTRACE == 1)
#  define NETWORKPROBE_IMPL_TRACE(X)
#else /* (NETWORKPROBE_IMPL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define NETWORKPROBE_IMPL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (NETWORKPROBE_IMPL_NTRACE == 1) */

#endif /* NETWORKPROBE_IMPL_EXPORT_H */

// End of auto generated file.
