// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:376


#include "OASIS_UUIDC.h"
#include "tao/CDR.h"
#include "tao/ORB_Core.h"

#if !defined (__ACE_INLINE__)
#include "OASIS_UUIDC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// .\be\be_visitor_sequence\sequence_cs.cpp:73

#if !defined (_OASIS_CHUNK_CS_)
#define _OASIS_CHUNK_CS_

OASIS::chunk::chunk (void)
{}

OASIS::chunk::chunk (
    ::CORBA::ULong length,
    ::CORBA::Octet * buffer,
    ::CORBA::Boolean release
  )
  : ::TAO::bounded_value_sequence<
        ::CORBA::Octet,
        8
      >
    (length, buffer, release)
{}

OASIS::chunk::chunk (
    const chunk &seq)
  : ::TAO::bounded_value_sequence<
        ::CORBA::Octet,
        8
      > (seq)
{}

OASIS::chunk::~chunk (void)
{}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// .\be\be_visitor_sequence\cdr_op_cs.cpp:96
#if !defined _TAO_CDR_OP_OASIS_chunk_CPP_
#define _TAO_CDR_OP_OASIS_chunk_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::chunk &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::chunk &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_OASIS_chunk_CPP_ */

// TAO_IDL - Generated from
// .\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::UUID &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.data1) &&
    (strm << _tao_aggregate.data2) &&
    (strm << _tao_aggregate.data3) &&
    (strm << _tao_aggregate.data4);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::UUID &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.data1) &&
    (strm >> _tao_aggregate.data2) &&
    (strm >> _tao_aggregate.data3) &&
    (strm >> _tao_aggregate.data4);
}

TAO_END_VERSIONED_NAMESPACE_DECL



