// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:152

#ifndef _TAO_IDL_COMMANDCHANNELC_KAJ3XT_H_
#define _TAO_IDL_COMMANDCHANNELC_KAJ3XT_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "OASIS_Tao_DataChannel_stub_export.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 1 || TAO_BETA_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO OASIS_TAO_DATACHANNEL_STUB_Export

// TAO_IDL - Generated from
// .\be\be_visitor_root\root_ch.cpp:160
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_module\module_ch.cpp:38

namespace OASIS
{

  // TAO_IDL - Generated from
  // .\be\be_interface.cpp:750

#if !defined (_OASIS_COMMANDCHANNEL__VAR_OUT_CH_)
#define _OASIS_COMMANDCHANNEL__VAR_OUT_CH_

  class CommandChannel;
  typedef CommandChannel *CommandChannel_ptr;

  typedef
    TAO_Objref_Var_T<
        CommandChannel
      >
    CommandChannel_var;
  
  typedef
    TAO_Objref_Out_T<
        CommandChannel
      >
    CommandChannel_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_interface\interface_ch.cpp:43

  class OASIS_TAO_DATACHANNEL_STUB_Export CommandChannel
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<CommandChannel>;

    // TAO_IDL - Generated from
    // .\be\be_type.cpp:307

    typedef CommandChannel_ptr _ptr_type;
    typedef CommandChannel_var _var_type;
    typedef CommandChannel_out _out_type;

    // The static operations.
    static CommandChannel_ptr _duplicate (CommandChannel_ptr obj);

    static void _tao_release (CommandChannel_ptr obj);

    static CommandChannel_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandChannel_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandChannel_ptr _nil (void);

    virtual void handle_command (
      const char * command);

    // TAO_IDL - Generated from
    // .\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    CommandChannel (void);

    // Concrete non-local interface only.
    CommandChannel (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    CommandChannel (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~CommandChannel (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    CommandChannel (const CommandChannel &);

    void operator= (const CommandChannel &);
  };

// TAO_IDL - Generated from
// .\be\be_visitor_module\module_ch.cpp:67

} // module OASIS

// TAO_IDL - Generated from
// .\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_OASIS_COMMANDCHANNEL__ARG_TRAITS_)
#define _OASIS_COMMANDCHANNEL__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::OASIS::CommandChannel>
    : public
        Object_Arg_Traits_T<
            ::OASIS::CommandChannel_ptr,
            ::OASIS::CommandChannel_var,
            ::OASIS::CommandChannel_out,
            TAO::Objref_Traits<OASIS::CommandChannel>,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_OASIS_COMMANDCHANNEL__TRAITS_)
#define _OASIS_COMMANDCHANNEL__TRAITS_

  template<>
  struct OASIS_TAO_DATACHANNEL_STUB_Export Objref_Traits< ::OASIS::CommandChannel>
  {
    static ::OASIS::CommandChannel_ptr duplicate (
        ::OASIS::CommandChannel_ptr p);
    static void release (
        ::OASIS::CommandChannel_ptr p);
    static ::OASIS::CommandChannel_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OASIS::CommandChannel_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_interface\cdr_op_ch.cpp:44

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OASIS_TAO_DATACHANNEL_STUB_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OASIS::CommandChannel_ptr );
OASIS_TAO_DATACHANNEL_STUB_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OASIS::CommandChannel_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "CommandChannelC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

