// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:376


#include "CommandChannelC.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "CommandChannelC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// .\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for OASIS::CommandChannel.

OASIS::CommandChannel_ptr
TAO::Objref_Traits<OASIS::CommandChannel>::duplicate (
    OASIS::CommandChannel_ptr p)
{
  return OASIS::CommandChannel::_duplicate (p);
}

void
TAO::Objref_Traits<OASIS::CommandChannel>::release (
    OASIS::CommandChannel_ptr p)
{
  ::CORBA::release (p);
}

OASIS::CommandChannel_ptr
TAO::Objref_Traits<OASIS::CommandChannel>::nil (void)
{
  return OASIS::CommandChannel::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<OASIS::CommandChannel>::marshal (
    const OASIS::CommandChannel_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// .\be\be_visitor_operation\operation_cs.cpp:91

void
OASIS::CommandChannel::handle_command (
  const char * command)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_command (command);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_command
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "handle_command",
      14,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (0, 0);
}

OASIS::CommandChannel::CommandChannel (void)
{
}

OASIS::CommandChannel::~CommandChannel (void)
{
}

OASIS::CommandChannel_ptr
OASIS::CommandChannel::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<CommandChannel>::narrow (
        _tao_objref,
        "IDL:OASIS/CommandChannel:1.0");
}

OASIS::CommandChannel_ptr
OASIS::CommandChannel::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<CommandChannel>::unchecked_narrow (
        _tao_objref);
}

OASIS::CommandChannel_ptr
OASIS::CommandChannel::_nil (void)
{
  return 0;
}

OASIS::CommandChannel_ptr
OASIS::CommandChannel::_duplicate (CommandChannel_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
OASIS::CommandChannel::_tao_release (CommandChannel_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
OASIS::CommandChannel::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:OASIS/CommandChannel:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* OASIS::CommandChannel::_interface_repository_id (void) const
{
  return "IDL:OASIS/CommandChannel:1.0";
}

::CORBA::Boolean
OASIS::CommandChannel::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// .\be\be_visitor_interface\cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::CommandChannel_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::CommandChannel_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::OASIS::CommandChannel RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



