// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:376


#include "DataChannelC.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/ORB_Core.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DataChannelC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// .\be\be_visitor_sequence\sequence_cs.cpp:73

#if !defined (_OASIS_BINARYDATA_CS_)
#define _OASIS_BINARYDATA_CS_

OASIS::BinaryData::BinaryData (void)
{}

OASIS::BinaryData::BinaryData (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence<
        ::CORBA::Octet
      > (max)
{}

OASIS::BinaryData::BinaryData (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::Octet * buffer,
    ::CORBA::Boolean release
  )
  : ::TAO::unbounded_value_sequence<
        ::CORBA::Octet
      >
    (max, length, buffer, release)
{}

OASIS::BinaryData::BinaryData (
    const BinaryData &seq)
  : ::TAO::unbounded_value_sequence<
        ::CORBA::Octet
      > (seq)
{}

OASIS::BinaryData::~BinaryData (void)
{}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// .\be\be_visitor_sequence\sequence_cs.cpp:73

#if !defined (_OASIS_SOFTWAREPROBEENTRYSEQ_CS_)
#define _OASIS_SOFTWAREPROBEENTRYSEQ_CS_

OASIS::SoftwareProbeEntrySeq::SoftwareProbeEntrySeq (void)
{}

OASIS::SoftwareProbeEntrySeq::SoftwareProbeEntrySeq (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence<
        SoftwareProbeEntry
      > (max)
{}

OASIS::SoftwareProbeEntrySeq::SoftwareProbeEntrySeq (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    OASIS::SoftwareProbeEntry * buffer,
    ::CORBA::Boolean release
  )
  : ::TAO::unbounded_value_sequence<
        SoftwareProbeEntry
      >
    (max, length, buffer, release)
{}

OASIS::SoftwareProbeEntrySeq::SoftwareProbeEntrySeq (
    const SoftwareProbeEntrySeq &seq)
  : ::TAO::unbounded_value_sequence<
        SoftwareProbeEntry
      > (seq)
{}

OASIS::SoftwareProbeEntrySeq::~SoftwareProbeEntrySeq (void)
{}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// .\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for OASIS::DataChannel.

OASIS::DataChannel_ptr
TAO::Objref_Traits<OASIS::DataChannel>::duplicate (
    OASIS::DataChannel_ptr p)
{
  return OASIS::DataChannel::_duplicate (p);
}

void
TAO::Objref_Traits<OASIS::DataChannel>::release (
    OASIS::DataChannel_ptr p)
{
  ::CORBA::release (p);
}

OASIS::DataChannel_ptr
TAO::Objref_Traits<OASIS::DataChannel>::nil (void)
{
  return OASIS::DataChannel::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<OASIS::DataChannel>::marshal (
    const OASIS::DataChannel_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// .\be\be_visitor_operation\operation_cs.cpp:91

void
OASIS::DataChannel::send_data (
  const ::OASIS::DataPacket & p)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::OASIS::DataPacket>::in_arg_val _tao_p (p);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_p
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "send_data",
      9,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_ONEWAY_INVOCATION
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// .\be\be_visitor_operation\operation_cs.cpp:91

void
OASIS::DataChannel::register_einode (
  const ::OASIS::EINodeRegistration & reg)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::OASIS::EINodeRegistration>::in_arg_val _tao_reg (reg);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_reg
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "register_einode",
      15,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// .\be\be_visitor_operation\operation_cs.cpp:91

void
OASIS::DataChannel::unregister_einode (
  const ::OASIS::UUID & uuid)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::OASIS::UUID>::in_arg_val _tao_uuid (uuid);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_uuid
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "unregister_einode",
      17,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (0, 0);
}

OASIS::DataChannel::DataChannel (void)
{
}

OASIS::DataChannel::~DataChannel (void)
{
}

OASIS::DataChannel_ptr
OASIS::DataChannel::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<DataChannel>::narrow (
        _tao_objref,
        "IDL:OASIS/DataChannel:1.0");
}

OASIS::DataChannel_ptr
OASIS::DataChannel::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<DataChannel>::unchecked_narrow (
        _tao_objref);
}

OASIS::DataChannel_ptr
OASIS::DataChannel::_nil (void)
{
  return 0;
}

OASIS::DataChannel_ptr
OASIS::DataChannel::_duplicate (DataChannel_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
OASIS::DataChannel::_tao_release (DataChannel_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
OASIS::DataChannel::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:OASIS/DataChannel:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* OASIS::DataChannel::_interface_repository_id (void) const
{
  return "IDL:OASIS/DataChannel:1.0";
}

::CORBA::Boolean
OASIS::DataChannel::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// .\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::TimeValue &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.sec) &&
    (strm << _tao_aggregate.usec);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::TimeValue &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.sec) &&
    (strm >> _tao_aggregate.usec);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_sequence\cdr_op_cs.cpp:96
#if !defined _TAO_CDR_OP_OASIS_BinaryData_CPP_
#define _TAO_CDR_OP_OASIS_BinaryData_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::BinaryData &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::BinaryData &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_OASIS_BinaryData_CPP_ */

// TAO_IDL - Generated from
// .\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::DataPacket &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.einode_uuid) &&
    (strm << _tao_aggregate.byte_order) &&
    (strm << _tao_aggregate.data);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::DataPacket &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.einode_uuid) &&
    (strm >> _tao_aggregate.byte_order) &&
    (strm >> _tao_aggregate.data);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::SoftwareProbeMetadata &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.uuid) &&
    (strm << _tao_aggregate.type.in ()) &&
    (strm << ::ACE_OutputCDR::from_octet (_tao_aggregate.version_major)) &&
    (strm << ::ACE_OutputCDR::from_octet (_tao_aggregate.version_minor)) &&
    (strm << _tao_aggregate.schema.in ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::SoftwareProbeMetadata &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.uuid) &&
    (strm >> _tao_aggregate.type.out ()) &&
    (strm >> ::ACE_InputCDR::to_octet (_tao_aggregate.version_major)) &&
    (strm >> ::ACE_InputCDR::to_octet (_tao_aggregate.version_minor)) &&
    (strm >> _tao_aggregate.schema.out ());
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::SoftwareProbeEntry &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.name.in ()) &&
    (strm << _tao_aggregate.metadata);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::SoftwareProbeEntry &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.name.out ()) &&
    (strm >> _tao_aggregate.metadata);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_sequence\cdr_op_cs.cpp:96
#if !defined _TAO_CDR_OP_OASIS_SoftwareProbeEntrySeq_CPP_
#define _TAO_CDR_OP_OASIS_SoftwareProbeEntrySeq_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::SoftwareProbeEntrySeq &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::SoftwareProbeEntrySeq &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_OASIS_SoftwareProbeEntrySeq_CPP_ */

// TAO_IDL - Generated from
// .\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::EINodeRegistration &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.uuid) &&
    (strm << _tao_aggregate.name.in ()) &&
    (strm << _tao_aggregate.probes) &&
    ::CORBA::Object::marshal (
        _tao_aggregate.cmd_channel.in (),
        strm
      );
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::EINodeRegistration &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.uuid) &&
    (strm >> _tao_aggregate.name.out ()) &&
    (strm >> _tao_aggregate.probes) &&
    (strm >> _tao_aggregate.cmd_channel.out ());
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_interface\cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OASIS::DataChannel_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OASIS::DataChannel_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::OASIS::DataChannel RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



