// -*- C++ -*-

#ifndef TEMPERATUREPROBEBRIDGE_V1_2_EXPORT_H
#define TEMPERATUREPROBEBRIDGE_V1_2_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL)
#  define TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL */

#if !defined (TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL)
#  define TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL 1
#endif /* ! TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL */

#if defined (TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL) && (TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL == 1)
#  if defined (TEMPERATUREPROBEBRIDGE_V1_2_BUILD_DLL)
#    define TEMPERATUREPROBEBRIDGE_V1_2_Export ACE_Proper_Export_Flag
#    define TEMPERATUREPROBEBRIDGE_V1_2_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TEMPERATUREPROBEBRIDGE_V1_2_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TEMPERATUREPROBEBRIDGE_V1_2_BUILD_DLL */
#    define TEMPERATUREPROBEBRIDGE_V1_2_Export ACE_Proper_Import_Flag
#    define TEMPERATUREPROBEBRIDGE_V1_2_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TEMPERATUREPROBEBRIDGE_V1_2_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TEMPERATUREPROBEBRIDGE_V1_2_BUILD_DLL */
#else /* TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL == 1 */
#  define TEMPERATUREPROBEBRIDGE_V1_2_Export
#  define TEMPERATUREPROBEBRIDGE_V1_2_SINGLETON_DECLARATION(T)
#  define TEMPERATUREPROBEBRIDGE_V1_2_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TEMPERATUREPROBEBRIDGE_V1_2_HAS_DLL == 1 */

// Set TEMPERATUREPROBEBRIDGE_V1_2_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (TEMPERATUREPROBEBRIDGE_V1_2_NTRACE)
#  if (ACE_NTRACE == 1)
#    define TEMPERATUREPROBEBRIDGE_V1_2_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define TEMPERATUREPROBEBRIDGE_V1_2_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !TEMPERATUREPROBEBRIDGE_V1_2_NTRACE */

#if (TEMPERATUREPROBEBRIDGE_V1_2_NTRACE == 1)
#  define TEMPERATUREPROBEBRIDGE_V1_2_TRACE(X)
#else /* (TEMPERATUREPROBEBRIDGE_V1_2_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define TEMPERATUREPROBEBRIDGE_V1_2_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (TEMPERATUREPROBEBRIDGE_V1_2_NTRACE == 1) */

#endif /* TEMPERATUREPROBEBRIDGE_V1_2_EXPORT_H */
