
// -*- C++ -*-
// $Id: Load_Configuration_export.h 1827 2011-08-12 15:38:20Z hillj $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl OASIS_LOAD_CONFIGURATION_TEST
// ------------------------------
#ifndef OASIS_LOAD_CONFIGURATION_TEST_EXPORT_H
#define OASIS_LOAD_CONFIGURATION_TEST_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL)
#  define OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL */

#if !defined (OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL)
#  define OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL 1
#endif /* ! OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL */

#if defined (OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL) && (OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL == 1)
#  if defined (OASIS_LOAD_CONFIGURATION_TEST_BUILD_DLL)
#    define OASIS_LOAD_CONFIGURATION_TEST_Export ACE_Proper_Export_Flag
#    define OASIS_LOAD_CONFIGURATION_TEST_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define OASIS_LOAD_CONFIGURATION_TEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* OASIS_LOAD_CONFIGURATION_TEST_BUILD_DLL */
#    define OASIS_LOAD_CONFIGURATION_TEST_Export ACE_Proper_Import_Flag
#    define OASIS_LOAD_CONFIGURATION_TEST_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define OASIS_LOAD_CONFIGURATION_TEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* OASIS_LOAD_CONFIGURATION_TEST_BUILD_DLL */
#else /* OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL == 1 */
#  define OASIS_LOAD_CONFIGURATION_TEST_Export
#  define OASIS_LOAD_CONFIGURATION_TEST_SINGLETON_DECLARATION(T)
#  define OASIS_LOAD_CONFIGURATION_TEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* OASIS_LOAD_CONFIGURATION_TEST_HAS_DLL == 1 */

// Set OASIS_LOAD_CONFIGURATION_TEST_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (OASIS_LOAD_CONFIGURATION_TEST_NTRACE)
#  if (ACE_NTRACE == 1)
#    define OASIS_LOAD_CONFIGURATION_TEST_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define OASIS_LOAD_CONFIGURATION_TEST_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !OASIS_LOAD_CONFIGURATION_TEST_NTRACE */

#if (OASIS_LOAD_CONFIGURATION_TEST_NTRACE == 1)
#  define OASIS_LOAD_CONFIGURATION_TEST_TRACE(X)
#else /* (OASIS_LOAD_CONFIGURATION_TEST_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define OASIS_LOAD_CONFIGURATION_TEST_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (OASIS_LOAD_CONFIGURATION_TEST_NTRACE == 1) */

#endif /* OASIS_LOAD_CONFIGURATION_TEST_EXPORT_H */

// End of auto generated file.
