
// -*- C++ -*-
// $Id: SwitchProbe_Impl_export.h 2214 2012-08-10 15:00:08Z dfeiock $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl SWITCHPROBE_IMPL
// ------------------------------
#ifndef SWITCHPROBE_IMPL_EXPORT_H
#define SWITCHPROBE_IMPL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (SWITCHPROBE_IMPL_HAS_DLL)
#  define SWITCHPROBE_IMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && SWITCHPROBE_IMPL_HAS_DLL */

#if !defined (SWITCHPROBE_IMPL_HAS_DLL)
#  define SWITCHPROBE_IMPL_HAS_DLL 1
#endif /* ! SWITCHPROBE_IMPL_HAS_DLL */

#if defined (SWITCHPROBE_IMPL_HAS_DLL) && (SWITCHPROBE_IMPL_HAS_DLL == 1)
#  if defined (SWITCHPROBE_IMPL_BUILD_DLL)
#    define SWITCHPROBE_IMPL_Export ACE_Proper_Export_Flag
#    define SWITCHPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define SWITCHPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* SWITCHPROBE_IMPL_BUILD_DLL */
#    define SWITCHPROBE_IMPL_Export ACE_Proper_Import_Flag
#    define SWITCHPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define SWITCHPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* SWITCHPROBE_IMPL_BUILD_DLL */
#else /* SWITCHPROBE_IMPL_HAS_DLL == 1 */
#  define SWITCHPROBE_IMPL_Export
#  define SWITCHPROBE_IMPL_SINGLETON_DECLARATION(T)
#  define SWITCHPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* SWITCHPROBE_IMPL_HAS_DLL == 1 */

// Set SWITCHPROBE_IMPL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (SWITCHPROBE_IMPL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define SWITCHPROBE_IMPL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define SWITCHPROBE_IMPL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !SWITCHPROBE_IMPL_NTRACE */

#if (SWITCHPROBE_IMPL_NTRACE == 1)
#  define SWITCHPROBE_IMPL_TRACE(X)
#else /* (SWITCHPROBE_IMPL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define SWITCHPROBE_IMPL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (SWITCHPROBE_IMPL_NTRACE == 1) */

#endif /* SWITCHPROBE_IMPL_EXPORT_H */

// End of auto generated file.
