
// -*- C++ -*-
// $Id: TemperatureProbe_Impl_Export.h 2012 2011-10-12 02:01:02Z dfeiock $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl TEMPERATUREPROBE_IMPL
// ------------------------------
#ifndef TEMPERATUREPROBE_IMPL_EXPORT_H
#define TEMPERATUREPROBE_IMPL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (TEMPERATUREPROBE_IMPL_HAS_DLL)
#  define TEMPERATUREPROBE_IMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TEMPERATUREPROBE_IMPL_HAS_DLL */

#if !defined (TEMPERATUREPROBE_IMPL_HAS_DLL)
#  define TEMPERATUREPROBE_IMPL_HAS_DLL 1
#endif /* ! TEMPERATUREPROBE_IMPL_HAS_DLL */

#if defined (TEMPERATUREPROBE_IMPL_HAS_DLL) && (TEMPERATUREPROBE_IMPL_HAS_DLL == 1)
#  if defined (TEMPERATUREPROBE_IMPL_BUILD_DLL)
#    define TEMPERATUREPROBE_IMPL_Export ACE_Proper_Export_Flag
#    define TEMPERATUREPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TEMPERATUREPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TEMPERATUREPROBE_IMPL_BUILD_DLL */
#    define TEMPERATUREPROBE_IMPL_Export ACE_Proper_Import_Flag
#    define TEMPERATUREPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TEMPERATUREPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TEMPERATUREPROBE_IMPL_BUILD_DLL */
#else /* TEMPERATUREPROBE_IMPL_HAS_DLL == 1 */
#  define TEMPERATUREPROBE_IMPL_Export
#  define TEMPERATUREPROBE_IMPL_SINGLETON_DECLARATION(T)
#  define TEMPERATUREPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TEMPERATUREPROBE_IMPL_HAS_DLL == 1 */

// Set TEMPERATUREPROBE_IMPL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (TEMPERATUREPROBE_IMPL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define TEMPERATUREPROBE_IMPL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define TEMPERATUREPROBE_IMPL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !TEMPERATUREPROBE_IMPL_NTRACE */

#if (TEMPERATUREPROBE_IMPL_NTRACE == 1)
#  define TEMPERATUREPROBE_IMPL_TRACE(X)
#else /* (TEMPERATUREPROBE_IMPL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define TEMPERATUREPROBE_IMPL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (TEMPERATUREPROBE_IMPL_NTRACE == 1) */

#endif /* TEMPERATUREPROBE_IMPL_EXPORT_H */

// End of auto generated file.
