
// -*- C++ -*-
// $Id: Memory_Footprint_Probe_Impl_export.h 2242 2013-08-22 15:38:08Z dfeiock $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl MEMORY_FOOTPRINT_PROBE_IMPL
// ------------------------------
#ifndef MEMORY_FOOTPRINT_PROBE_IMPL_EXPORT_H
#define MEMORY_FOOTPRINT_PROBE_IMPL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL)
#  define MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL */

#if !defined (MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL)
#  define MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL 1
#endif /* ! MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL */

#if defined (MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL) && (MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL == 1)
#  if defined (MEMORY_FOOTPRINT_PROBE_IMPL_BUILD_DLL)
#    define MEMORY_FOOTPRINT_PROBE_IMPL_Export ACE_Proper_Export_Flag
#    define MEMORY_FOOTPRINT_PROBE_IMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define MEMORY_FOOTPRINT_PROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* MEMORY_FOOTPRINT_PROBE_IMPL_BUILD_DLL */
#    define MEMORY_FOOTPRINT_PROBE_IMPL_Export ACE_Proper_Import_Flag
#    define MEMORY_FOOTPRINT_PROBE_IMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define MEMORY_FOOTPRINT_PROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* MEMORY_FOOTPRINT_PROBE_IMPL_BUILD_DLL */
#else /* MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL == 1 */
#  define MEMORY_FOOTPRINT_PROBE_IMPL_Export
#  define MEMORY_FOOTPRINT_PROBE_IMPL_SINGLETON_DECLARATION(T)
#  define MEMORY_FOOTPRINT_PROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* MEMORY_FOOTPRINT_PROBE_IMPL_HAS_DLL == 1 */

// Set MEMORY_FOOTPRINT_PROBE_IMPL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (MEMORY_FOOTPRINT_PROBE_IMPL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define MEMORY_FOOTPRINT_PROBE_IMPL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define MEMORY_FOOTPRINT_PROBE_IMPL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !MEMORY_FOOTPRINT_PROBE_IMPL_NTRACE */

#if (MEMORY_FOOTPRINT_PROBE_IMPL_NTRACE == 1)
#  define MEMORY_FOOTPRINT_PROBE_IMPL_TRACE(X)
#else /* (MEMORY_FOOTPRINT_PROBE_IMPL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define MEMORY_FOOTPRINT_PROBE_IMPL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (MEMORY_FOOTPRINT_PROBE_IMPL_NTRACE == 1) */

#endif /* MEMORY_FOOTPRINT_PROBE_IMPL_EXPORT_H */

// End of auto generated file.
