
// -*- C++ -*-
// $Id: HeartbeatSoftwareProbe_export.h 1754 2011-02-20 23:56:20Z owensh $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl HEARTBEAT_SOFTWARE_PROBE
// ------------------------------
#ifndef HEARTBEAT_SOFTWARE_PROBE_EXPORT_H
#define HEARTBEAT_SOFTWARE_PROBE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (HEARTBEAT_SOFTWARE_PROBE_HAS_DLL)
#  define HEARTBEAT_SOFTWARE_PROBE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && HEARTBEAT_SOFTWARE_PROBE_HAS_DLL */

#if !defined (HEARTBEAT_SOFTWARE_PROBE_HAS_DLL)
#  define HEARTBEAT_SOFTWARE_PROBE_HAS_DLL 1
#endif /* ! HEARTBEAT_SOFTWARE_PROBE_HAS_DLL */

#if defined (HEARTBEAT_SOFTWARE_PROBE_HAS_DLL) && (HEARTBEAT_SOFTWARE_PROBE_HAS_DLL == 1)
#  if defined (HEARTBEAT_SOFTWARE_PROBE_BUILD_DLL)
#    define HEARTBEAT_SOFTWARE_PROBE_Export ACE_Proper_Export_Flag
#    define HEARTBEAT_SOFTWARE_PROBE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define HEARTBEAT_SOFTWARE_PROBE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* HEARTBEAT_SOFTWARE_PROBE_BUILD_DLL */
#    define HEARTBEAT_SOFTWARE_PROBE_Export ACE_Proper_Import_Flag
#    define HEARTBEAT_SOFTWARE_PROBE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define HEARTBEAT_SOFTWARE_PROBE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* HEARTBEAT_SOFTWARE_PROBE_BUILD_DLL */
#else /* HEARTBEAT_SOFTWARE_PROBE_HAS_DLL == 1 */
#  define HEARTBEAT_SOFTWARE_PROBE_Export
#  define HEARTBEAT_SOFTWARE_PROBE_SINGLETON_DECLARATION(T)
#  define HEARTBEAT_SOFTWARE_PROBE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* HEARTBEAT_SOFTWARE_PROBE_HAS_DLL == 1 */

// Set HEARTBEAT_SOFTWARE_PROBE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (HEARTBEAT_SOFTWARE_PROBE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define HEARTBEAT_SOFTWARE_PROBE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define HEARTBEAT_SOFTWARE_PROBE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !HEARTBEAT_SOFTWARE_PROBE_NTRACE */

#if (HEARTBEAT_SOFTWARE_PROBE_NTRACE == 1)
#  define HEARTBEAT_SOFTWARE_PROBE_TRACE(X)
#else /* (HEARTBEAT_SOFTWARE_PROBE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define HEARTBEAT_SOFTWARE_PROBE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (HEARTBEAT_SOFTWARE_PROBE_NTRACE == 1) */

#endif /* HEARTBEAT_SOFTWARE_PROBE_EXPORT_H */

// End of auto generated file.
