
// -*- C++ -*-
// $Id: HeartbeatProbe_Impl_export.h 1762 2011-02-27 03:03:12Z hillj $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl HEARTBEATPROBE_IMPL
// ------------------------------
#ifndef HEARTBEATPROBE_IMPL_EXPORT_H
#define HEARTBEATPROBE_IMPL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (HEARTBEATPROBE_IMPL_HAS_DLL)
#  define HEARTBEATPROBE_IMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && HEARTBEATPROBE_IMPL_HAS_DLL */

#if !defined (HEARTBEATPROBE_IMPL_HAS_DLL)
#  define HEARTBEATPROBE_IMPL_HAS_DLL 1
#endif /* ! HEARTBEATPROBE_IMPL_HAS_DLL */

#if defined (HEARTBEATPROBE_IMPL_HAS_DLL) && (HEARTBEATPROBE_IMPL_HAS_DLL == 1)
#  if defined (HEARTBEATPROBE_IMPL_BUILD_DLL)
#    define HEARTBEATPROBE_IMPL_Export ACE_Proper_Export_Flag
#    define HEARTBEATPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define HEARTBEATPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* HEARTBEATPROBE_IMPL_BUILD_DLL */
#    define HEARTBEATPROBE_IMPL_Export ACE_Proper_Import_Flag
#    define HEARTBEATPROBE_IMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define HEARTBEATPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* HEARTBEATPROBE_IMPL_BUILD_DLL */
#else /* HEARTBEATPROBE_IMPL_HAS_DLL == 1 */
#  define HEARTBEATPROBE_IMPL_Export
#  define HEARTBEATPROBE_IMPL_SINGLETON_DECLARATION(T)
#  define HEARTBEATPROBE_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* HEARTBEATPROBE_IMPL_HAS_DLL == 1 */

// Set HEARTBEATPROBE_IMPL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (HEARTBEATPROBE_IMPL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define HEARTBEATPROBE_IMPL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define HEARTBEATPROBE_IMPL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !HEARTBEATPROBE_IMPL_NTRACE */

#if (HEARTBEATPROBE_IMPL_NTRACE == 1)
#  define HEARTBEATPROBE_IMPL_TRACE(X)
#else /* (HEARTBEATPROBE_IMPL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define HEARTBEATPROBE_IMPL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (HEARTBEATPROBE_IMPL_NTRACE == 1) */

#endif /* HEARTBEATPROBE_IMPL_EXPORT_H */

// End of auto generated file.
