
// -*- C++ -*-
// $Id: Data_Channel_Publisher_export.h 1964 2011-10-03 02:59:33Z hillj $
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl OASIS_TENA_DATACHANNEL_PUBLISHER
// ------------------------------
#ifndef OASIS_TENA_DATACHANNEL_PUBLISHER_EXPORT_H
#define OASIS_TENA_DATACHANNEL_PUBLISHER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL)
#  define OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL */

#if !defined (OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL)
#  define OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL 1
#endif /* ! OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL */

#if defined (OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL) && (OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL == 1)
#  if defined (OASIS_TENA_DATACHANNEL_PUBLISHER_BUILD_DLL)
#    define OASIS_TENA_DATACHANNEL_PUBLISHER_Export ACE_Proper_Export_Flag
#    define OASIS_TENA_DATACHANNEL_PUBLISHER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define OASIS_TENA_DATACHANNEL_PUBLISHER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* OASIS_TENA_DATACHANNEL_PUBLISHER_BUILD_DLL */
#    define OASIS_TENA_DATACHANNEL_PUBLISHER_Export ACE_Proper_Import_Flag
#    define OASIS_TENA_DATACHANNEL_PUBLISHER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define OASIS_TENA_DATACHANNEL_PUBLISHER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* OASIS_TENA_DATACHANNEL_PUBLISHER_BUILD_DLL */
#else /* OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL == 1 */
#  define OASIS_TENA_DATACHANNEL_PUBLISHER_Export
#  define OASIS_TENA_DATACHANNEL_PUBLISHER_SINGLETON_DECLARATION(T)
#  define OASIS_TENA_DATACHANNEL_PUBLISHER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* OASIS_TENA_DATACHANNEL_PUBLISHER_HAS_DLL == 1 */

// Set OASIS_TENA_DATACHANNEL_PUBLISHER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (OASIS_TENA_DATACHANNEL_PUBLISHER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define OASIS_TENA_DATACHANNEL_PUBLISHER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define OASIS_TENA_DATACHANNEL_PUBLISHER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !OASIS_TENA_DATACHANNEL_PUBLISHER_NTRACE */

#if (OASIS_TENA_DATACHANNEL_PUBLISHER_NTRACE == 1)
#  define OASIS_TENA_DATACHANNEL_PUBLISHER_TRACE(X)
#else /* (OASIS_TENA_DATACHANNEL_PUBLISHER_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define OASIS_TENA_DATACHANNEL_PUBLISHER_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (OASIS_TENA_DATACHANNEL_PUBLISHER_NTRACE == 1) */

#endif /* OASIS_TENA_DATACHANNEL_PUBLISHER_EXPORT_H */

// End of auto generated file.
