// -*- C++ -*-

#ifndef PROCESSORPROBEBRIDGE_V1_0_EXPORT_H
#define PROCESSORPROBEBRIDGE_V1_0_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (PROCESSORPROBEBRIDGE_V1_0_HAS_DLL)
#  define PROCESSORPROBEBRIDGE_V1_0_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && PROCESSORPROBEBRIDGE_V1_0_HAS_DLL */

#if !defined (PROCESSORPROBEBRIDGE_V1_0_HAS_DLL)
#  define PROCESSORPROBEBRIDGE_V1_0_HAS_DLL 1
#endif /* ! PROCESSORPROBEBRIDGE_V1_0_HAS_DLL */

#if defined (PROCESSORPROBEBRIDGE_V1_0_HAS_DLL) && (PROCESSORPROBEBRIDGE_V1_0_HAS_DLL == 1)
#  if defined (PROCESSORPROBEBRIDGE_V1_0_BUILD_DLL)
#    define PROCESSORPROBEBRIDGE_V1_0_Export ACE_Proper_Export_Flag
#    define PROCESSORPROBEBRIDGE_V1_0_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define PROCESSORPROBEBRIDGE_V1_0_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* PROCESSORPROBEBRIDGE_V1_0_BUILD_DLL */
#    define PROCESSORPROBEBRIDGE_V1_0_Export ACE_Proper_Import_Flag
#    define PROCESSORPROBEBRIDGE_V1_0_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define PROCESSORPROBEBRIDGE_V1_0_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* PROCESSORPROBEBRIDGE_V1_0_BUILD_DLL */
#else /* PROCESSORPROBEBRIDGE_V1_0_HAS_DLL == 1 */
#  define PROCESSORPROBEBRIDGE_V1_0_Export
#  define PROCESSORPROBEBRIDGE_V1_0_SINGLETON_DECLARATION(T)
#  define PROCESSORPROBEBRIDGE_V1_0_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* PROCESSORPROBEBRIDGE_V1_0_HAS_DLL == 1 */

// Set PROCESSORPROBEBRIDGE_V1_0_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (PROCESSORPROBEBRIDGE_V1_0_NTRACE)
#  if (ACE_NTRACE == 1)
#    define PROCESSORPROBEBRIDGE_V1_0_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define PROCESSORPROBEBRIDGE_V1_0_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !PROCESSORPROBEBRIDGE_V1_0_NTRACE */

#if (PROCESSORPROBEBRIDGE_V1_0_NTRACE == 1)
#  define PROCESSORPROBEBRIDGE_V1_0_TRACE(X)
#else /* (PROCESSORPROBEBRIDGE_V1_0_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define PROCESSORPROBEBRIDGE_V1_0_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (PROCESSORPROBEBRIDGE_V1_0_NTRACE == 1) */

#endif /* PROCESSORPROBEBRIDGE_V1_0_EXPORT_H */
